name: Trade
version: 1.0
main: PTK\Trade\Main
author: PTK-KienPham
description: Plugin Trade Bởi PTK-KienPham
api: [2.0.0, 3.0.0]
commands:
 trade:
  usage: /trade list để xem danh sách đặc biệt
  default: true