name: FlyText[PTK] 
main: PTK\FlyText\Main
version: 1.0
api: [2.0.0, 3.0.0]
author: PTK-KienPham

commands:
  addtext:
    desctiption: Thêm chữ bay
    permission: flytext.addtext
permissions:
  flytext:
    default: op
    desctiption: Top permission
    childrem:
      flytext.addtext:
        default: op
        desctiption: Tạo chữ bay